FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV TRANSFORMERS_CACHE=/app/cache
ENV HF_HUB_DISABLE_SYMLINKS_WARNING=1

WORKDIR /app
RUN apt-get update && apt-get install -y libsndfile1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

# 🔽 Descarga el modelo durante el build
RUN python -c "from transformers import Wav2Vec2ForCTC, AutoTokenizer, AutoFeatureExtractor; Wav2Vec2ForCTC.from_pretrained('facebook/mms-1b-all'); AutoTokenizer.from_pretrained('facebook/mms-1b-all'); AutoFeatureExtractor.from_pretrained('facebook/mms-1b-all')"
EXPOSE 8080
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8080"]